# SchemDraw is a drawing package of python. version 7.01 is used to draw this circuits schematic diagram.
# This version should be installed in system.
# We didn't use the latest version of SchemDraw for a bug, which creates problem to save the drawing.

import SchemDraw
import SchemDraw.elements as elm

d=SchemDraw.Drawing()

source=d.add(elm.SourceSin,d='up',label='Vg')
d.add(elm.Line(d='down',l=d.unit/3,xy=source.start))
d.add(elm.Ground(color='blue'))
d.add(elm.Line(d='right',l=d.unit/5,xy=source.end))
d.add(elm.Resistor(d='right',color='red',l=d.unit/5,label='Rg'))
d.add(elm.Line(d='right',l=d.unit/7))
d.add(elm.Capacitor(d='right',color='blue',l=d.unit/6))
d.add(elm.Line(d='right',l=d.unit/7))
d1=d.add(elm.Dot)
d.add(elm.Line(d='up',l=d.unit/5,xy=d1.start))
d.add(elm.Resistor(d='up',l=d.unit/5,label='R1',color='red'))
d.add(elm.Line(d='up',l=d.unit/5))
d.add(elm.Line(d='right',l=d.unit*1))
d2=d.add(elm.Dot)
d.add(elm.Line(d='down',l=d.unit/5,xy=d2.start))
d.add(elm.Resistor(d='down',l=d.unit/5,label='Rc',color='red'))
d.add(elm.Line(d='down',l=d.unit/5))
d3=d.add(elm.Dot)
d.add(elm.Line(d='down',l=d.unit/4,xy=d1.start))
d4=d.add(elm.Dot)
line1=d.add(elm.Line(d='right',l=d.unit/1.34))
q1=d.add(elm.BjtNpn(xy=line1.end,color='green',label='Q1'))
d.add(elm.Line(d='down',at=(q1,'emitter'),l=d.unit/5))
d5=d.add(elm.Dot)
d.add(elm.Resistor(d='down',color='red',l=d.unit/2,label='Re'))
d.add(elm.Line(d='down',l=d.unit/5))
d.add(elm.Ground(color='blue'))
d.add(elm.Line(d='down',l=d.unit/2.5,xy=d4.start))
d.add(elm.Resistor(d='down',color='red',l=d.unit/2,label='R2'))
d.add(elm.Line(d='down',l=d.unit/5))
d.add(elm.Ground(color='blue'))
d.add(elm.Line(d='right',xy=d2.start,l=d.unit*1.1))
d6=d.add(elm.Dot)
d.add(elm.Line(d='right',xy=d3.start,l=d.unit/3.5))
d.add(elm.Capacitor(d='right',color='blue',l=d.unit/2))
d.add(elm.Line(d='right',to=(9.25,3.02)))
d7=d.add(elm.Dot)
d.add(elm.Line(d='down',l=d.unit/5,xy=d6.start))
d.add(elm.Resistor(d='down',color='red',l=d.unit/3,label='R1'))
d.add(elm.Line(d='down',to=d7.start))
d.add(elm.Line(d='down',l=d.unit/4))
d8=d.add(elm.Dot)
d.add(elm.Line(d='right',l=d.unit/2,xy=d5.start))
d.add(elm.Line(d='down',l=d.unit/5))
d.add(elm.Capacitor(d='down',l=d.unit/2,color='blue'))
d.add(elm.Ground(color='blue'))
d.add(elm.Line(xy=d8.start,d='down',l=d.unit/2.4))
d.add(elm.Resistor(d='down',color='red',l=d.unit/2,label='R2'))
d.add(elm.Line(d='down',l=d.unit/5))
d.add(elm.Ground(color='blue'))
line2=d.add(elm.Line(xy=d8.start,d='right',l=d.unit/1.34))
q2=d.add(elm.BjtNpn(xy=line2.end,color='green',label='Q2'))
d.add(elm.Line(at=(q2,'emitter'),d='down',l=d.unit/5))
d11=d.add(elm.Dot)
d.add(elm.Resistor(label='Re',color='red',l=d.unit/2))
d.add(elm.Line(d='down',l=d.unit/6))
d.add(elm.Ground(color='blue'))
d.add(elm.Line(xy=d6.start,d='right'))
d9=d.add(elm.Dot)
d.add(elm.Line(d='down',l=d.unit/5,xy=d9.start))
d.add(elm.Resistor(d='down',l=d.unit/3,color='red',label='Rc'))
d.add(elm.Line(d='down',l=d.unit/5))
d10=d.add(elm.Dot)
d.add(elm.Line(d='right',l=d.unit/2,xy=d10.start))
d.add(elm.Capacitor(d='right',color='blue',l=d.unit/4))
d.add(elm.Line(d='right',l=d.unit/2))
d.add(elm.Line(d='down',l=d.unit/2.4))
d.add(elm.Resistor(d='down',l=d.unit/2,color='red',label='Rl'))
d.add(elm.Line(d='down',l=d.unit/2.4))
d.add(elm.Ground(color='blue'))
d.add(elm.Line(d='right',l=d.unit/2,xy=d11.start))
d.add(elm.Line(d='down',l=d.unit/6))
d.add(elm.Capacitor(d='down',l=d.unit/2,color='blue'))
d.add(elm.Ground(color='blue'))
d.add(elm.LineDot(label='+Vcc',xy=d9.start,d='right'))

d.draw()
